baseurl = "/"
languageCode = "en-us"
theme = "mainroad"
pagination.pagerSize = 10 # Number of posts per page
pluralizeListTitles = false

[Params.logo]
    title = "Geoff in the Garage"
    subtitle = "OK, maybe not *every* day..."

[Params]
    mainSections = ["blog", "projects"]
    post_meta = ["date"]
    dateformat = "Monday, Jan 2, 2006"
    pager = true
    readmore = false
    goatcounter = "geoffinthegarage"

[Params.style.vars]
    highlightColor = "#05af41"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["social", "taglist"]

[Params.widgets]
    recent_num = 5
    tags_counter = false

[Params.widgets.social]
    github = "geoffworks17"

[[Params.widgets.social.custom]]
  title = "YouTube"
  url = "https://youtube.com/c/geoffworks17"
  icon = "svg/youtube.svg" # Optional. Path relative to "layouts/partials"

[menu]
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        #layout = "list"
        weight = 3

    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "post"
        name = "Blog"
        url = "/blog/"
        weight = 2

    [[menu.main]]
        identifier = "shop"
        name = "Shop"
        url = "https://geoffinthegarage.bigcartel.com/"
        weight = 4

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 5

    [[menu.side]]